### ISSUE TITLE
Time mode requires the flot.time plugin.

### ISSUE THREAD

**Issue by arthurkoch** [black-mirror-1/singlestat-math#1]
Hey,

after the first refresh, the graphs (not the singlestat panels) stop displaying, and I get this error message:

```
Time mode requires the flot.time plugin.

Error: Time mode requires the flot.time plugin.
    at setupTickGeneration (http://grafana.jvm.de:3000/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:1773:23)
    at Object.eval (http://grafana.jvm.de:3000/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:1629:25)
    at Function.each (http://grafana.jvm.de:3000/public/build/vendor.0cea50118711e7e6c839.js:72:14819)
    at setupGrid (http://grafana.jvm.de:3000/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:1627:23)
    at new Plot (http://grafana.jvm.de:3000/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:716:9)
    at Function.$.plot (http://grafana.jvm.de:3000/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:3196:20)
    at p (http://grafana.jvm.de:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:219619)
    at l (http://grafana.jvm.de:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:218811)
    at o.<anonymous> (http://grafana.jvm.de:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:224696)
    at o.emit (http://grafana.jvm.de:3000/public/build/vendor.0cea50118711e7e6c839.js:44:25321)
```

Grafana Version 5.1.3

**Comment by ssirois** [comment]
I can reproduce with Grafana v5.1.3 (commit: 087143285) _latest when writing this comment_

Both grafana core and this panel plugin use same `jquery.flot.js` version (0.8.3).

I'll try to investigate further to see if I can manage to create a PR on this.

**Comment by black-mirror-1** [comment]
Should be fixed now! I included the extra libraries

**Comment by ssirois** [comment]
OK thank you. I have created #2 so that the `dist` folder represents the latest version.
